import "./globals.css";

import type { Metadata } from "next";
import { WithProgressBar } from "next-progress-bar";
import Link from "next/link";
import { NavigationInterceptionProvider } from "@yaredfall/next-navigation-interception";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <WithProgressBar>
                    <NavigationInterceptionProvider>
                        <div className="flex gap-4">
                            {["page1", "page2", "guarded"].map((l) => (
                                <Link key={l} href={"/" + l}>
                                    to {l}
                                </Link>
                            ))}
                        </div>
                        {children}
                    </NavigationInterceptionProvider>
                </WithProgressBar>
            </body>
        </html>
    );
}
