import type { Metadata } from "next";
import "./globals.css";
import { WithProgressBar } from "next-progress-bar";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <WithProgressBar>
                    <div className="flex gap-4">
                        {["page1", "page2"].map((l) => (
                            <Link key={l} href={"/" + l}>
                                to {l}
                            </Link>
                        ))}
                    </div>
                    {children}
                </WithProgressBar>
            </body>
        </html>
    );
}
